name: nmbmkononi
description: National Microfinance Bank
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons:
  flutter_svg: ^0.18.0
  adobe_xd: ^1.0.0
  url_launcher: ^5.0.3
  splashscreen: ^1.2.0
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true
  assets:
    - assets/images/

